# This workflow builds all the projects and publishes them on s3
name: Deploy projects

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
    inputs:
      message:
        description: 'Commit message'
        required: false
        default: 'Bump npm dependencies'
  repository_dispatch:
    types: [deploy]

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::195732290078:role/github_oidc_role_projects
          aws-region: eu-west-1

      - name: Sync to s3
        run: |
          aws s3 ls 


